### ISSUE TITLE
FGFS Nightly Fatal Exception

### ISSUE THREAD

**Issue by owenexplorerph** [Octal450/MD-11#15] opened 2021-01-14 12:38 UTC
**Describe the bug**
MD-11 crashed after this window: 
Fatal exception
function/method call on uncallable object.

**Expected behaviour**
During normal takeoff, this should not happen.

**Screenshots**
![md-11](https://user-images.githubusercontent.com/77441038/104591915-5c6bdf80-56a8-11eb-9aee-1246729ac023.jpg)

**System:**
 - OS: Windows 10 20H2
 - FlightGear version: 2020.4

**Comment by Octal450** [comment] 2021-01-14 13:35
Hi,
Please provide fgfs.log That error itself tells me nothing as I can't reproduce this. Could be an issue with the nightly, I currently tested on 2020.3.5, 2020.4 doesn't launch on my Windows 7 Main PC at this moment. I will try it on my Windows 10 20H2 later.

Kind Regards,
Josh

**Comment by Octal450** [comment] 2021-01-14 13:56
![image](https://user-images.githubusercontent.com/25598604/104599934-5cd38e80-5646-11eb-9634-512b8aa859fa.png)
Can't reproduce, tried to put the aircraft in the same situation you had, with speed protection kicking in on the climbout. 20H2, latest 2020.4 nightly. Will need an fgfs.log.

Kind Regards,
Josh

**Comment by owenexplorerph** [comment] 2021-01-15 03:29
The issue cleared up on the second attempt, and I don't know how to send a
fgfs.log.
FlightGear did not open a window asking about the error log.

Kind Regards,
Owen Explorer
@owenexplorerph

**Comment by Octal450** [comment] 2021-01-15 03:50
Hi,
The file is stored in %appdata%\flightgear.org and is called fgfs.log. Note that this changes every time you launch the sim, so you'd need to send me all the fgfs.log files you see there and I can look through them, I believe it stores 10 files.

Going to close the issue for now as it looks like it may have been a one off FGFS bug rather than an MD-11 bug, but lets continue to check it out.

Kind Regards,
Josh

**Closed by Octal450** 2021-01-15 03:50 UTC
Labels: bug, can't reproduce

**Comment by owenexplorerph** [comment] 2021-01-15 07:58
I agree that this issue can be properly closed. The aircraft is good and I
congratulate the efforts. Godspeed to further add the simulation realism to
this airplane.

Kind Regards,
Owen Explorer
@owenexplorerph

**Comment by Octal450** [comment] 2021-01-15 16:23
Thanks a lot for the compliments! If you do encounter it again, please capture the fgfs.log file for me, that would be massively helpful to see!

Happy landings!
Kind Regards,
Josh
