### ISSUE TITLE
MD-11 sound

### ISSUE THREAD

**Issue by BobSimulator2020** [Octal450/MD-11#42] opened 2024-07-30 13:59 UTC
When I try to land the md 11, no touchdown sounds play. Also, sometimes when starting up the aircraft manually, there is not sound at all. Also during landing, no GPWS callouts are heard. Please fix this and thanks! :D

**Comment by Octal450** [comment] 2024-07-30 19:47
You didn't follow the template. Closing.

Also, can't reproduce. 

Josh

**Closed by Octal450** 2024-07-30 19:47 UTC
